CREATE TABLE IF NOT EXISTS anniversary (
    id BIGINT NOT NULL AUTO_INCREMENT COMMENT '主键ID',
    user_id BIGINT NOT NULL COMMENT '创建人ID',
    title VARCHAR(100) NOT NULL COMMENT '纪念日名称',
    type VARCHAR(32) NOT NULL COMMENT '纪念日类型 LOVE_DAY/BIRTHDAY/MEMORY_DAY/CUSTOM',
    calendar_type VARCHAR(16) NOT NULL DEFAULT 'SOLAR' COMMENT '日期类型 SOLAR/LUNAR',
    anniversary_date DATE NOT NULL COMMENT '纪念日日期',
    lunar_year INT DEFAULT NULL COMMENT '农历年',
    lunar_month INT DEFAULT NULL COMMENT '农历月',
    lunar_day INT DEFAULT NULL COMMENT '农历日',
    lunar_leap_month TINYINT(1) DEFAULT NULL COMMENT '是否闰月',
    relation_scope VARCHAR(32) NOT NULL COMMENT '纪念日归属 SELF/PARTNER/BOTH',
    repeat_type VARCHAR(32) NOT NULL DEFAULT 'YEARLY' COMMENT '重复方式 ONCE/YEARLY',
    reminder_days INT DEFAULT NULL COMMENT '提前提醒天数',
    cover_photo_id BIGINT DEFAULT NULL COMMENT '封面照片ID',
    description VARCHAR(255) DEFAULT NULL COMMENT '纪念日说明',
    create_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    update_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    is_deleted TINYINT NOT NULL DEFAULT 0 COMMENT '逻辑删除 0否 1是',
    PRIMARY KEY (id),
    KEY idx_anniversary_user_id (user_id),
    KEY idx_anniversary_date (anniversary_date),
    CONSTRAINT fk_anniversary_user FOREIGN KEY (user_id) REFERENCES user (id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='纪念日表';
